name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git semantic version
      id: semver
      uses: paulhatch/semantic-version@v5.3.0
      with:
        major_pattern: '/^(breaking|major)/i'
        minor_pattern: '/^(feat|feature|minor)/i'
        patch_pattern: '/^(fix|patch)/i'
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"


    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo 'Logging in to Docker Hub...'
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo 'Docker login successful'

    - name: Build docker image
      env:
        NEW_VERSION: ${{ steps.semver.outputs.version }}
      run: |
        echo 'Building Docker image...'
        docker build -t seysww/docker-graphql:$NEW_VERSION .
        docker build -t seysww/docker-graphql:latest .
        echo 'Docker image built successfully'

    - name: Push docker image
      env:
        NEW_VERSION: ${{ steps.semver.outputs.version }}
      run: |
        echo 'Pushing Docker image...'
        docker push seysww/docker-graphql:$NEW_VERSION
        docker push seysww/docker-graphql:latest
        echo 'Docker image pushed successfully'
        

    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
